// ============================================================================
// GatewayController.cs - Gateway Status and Health Check Endpoints
// ============================================================================
// This controller provides operational endpoints for monitoring the API Gateway.
// It exposes:
//   GET /api/gateway/health  - public health check (no auth required)
//   GET /api/gateway/status  - authenticated status for active SSE connections
//     and the current event bus backend
//
// These endpoints are commonly used by load balancers, Kubernetes probes, and
// operational dashboards to verify the gateway is running correctly.
// ============================================================================

using FinancialPlatform.EventInfrastructure.Bus;
using FinancialPlatform.Shared.Enums;
using FinancialPlatform.Shared.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FinancialPlatform.ApiGateway.Controllers;

[ApiController]
[Route("api/gateway")]
public class GatewayController : ControllerBase
{
    // --------------------------------------------------------------------------
    // Private fields - dependencies injected via the constructor.
    // By convention in C#, private fields are prefixed with an underscore (_).
    //
    // ISseHub is an interface - a contract that defines methods without
    // implementation. The actual implementation (InMemorySseHub) is registered
    // in Program.cs via AddSingleton<ISseHub, InMemorySseHub>(). Using
    // interfaces enables swapping implementations (e.g., a Redis-backed hub)
    // without changing this controller.
    //
    // "readonly" prevents reassignment after construction, which is a safety
    // guarantee - injected dependencies should not be replaced at runtime.
    // --------------------------------------------------------------------------
    private readonly ISseHub _sseHub;
    private readonly AdaptiveEventBus _eventBus;
    private readonly IConfiguration _config;
    private readonly IHttpClientFactory _httpClientFactory;

    // --------------------------------------------------------------------------
    // Constructor with dependency injection.
    //
    // IConfiguration is a built-in ASP.NET Core interface for reading
    // configuration values from appsettings.json, environment variables,
    // command-line arguments, and other sources.
    //
    // IEventBus is received as the interface type and then cast to the
    // concrete AdaptiveEventBus type. This cast "(AdaptiveEventBus)eventBus"
    // is a "downcast" - converting from a base/interface type to a more
    // specific derived type. It will throw if the actual object is not
    // an AdaptiveEventBus.
    //
    // IHttpClientFactory creates HttpClient instances for making outbound
    // HTTP calls (e.g., health-checking other services).
    // --------------------------------------------------------------------------
    public GatewayController(ISseHub sseHub, IEventBus eventBus, IConfiguration config, IHttpClientFactory httpClientFactory)
    {
        _sseHub = sseHub;
        _eventBus = (AdaptiveEventBus)eventBus;
        _config = config;
        _httpClientFactory = httpClientFactory;
    }

    // --------------------------------------------------------------------------
    // [HttpGet("health")] - Maps this method to HTTP GET /api/gateway/health.
    //   There is no [Authorize] attribute, so this endpoint is publicly
    //   accessible without authentication.
    // --------------------------------------------------------------------------
    [HttpGet("health")]
    public async Task<IActionResult> Health()
    {
        // --------------------------------------------------------------------------
        // Dictionary<string, object> - a key-value map where keys are strings
        // and values can be any type (object is the base type of all types in C#,
        // similar to "any" in TypeScript).
        //
        // The ["key"] = value syntax inside collection initializers adds entries
        // to the dictionary. This is equivalent to:
        //   dict["ApiGateway"] = new { Status = "Healthy", ... };
        //
        // "new { Status = "Healthy", Port = 5000 }" creates an anonymous type -
        // a class with read-only properties generated by the compiler. This is
        // similar to object literals in JavaScript: { status: "Healthy", port: 5000 }.
        // --------------------------------------------------------------------------
        var services = new Dictionary<string, object>
        {
            ["ApiGateway"] = new { Status = "Healthy", Port = 5000 },
            // _config["ServiceUrls:TransactionService"] reads a nested config value.
            // The colon ":" navigates the JSON hierarchy:
            //   { "ServiceUrls": { "TransactionService": "http://..." } }
            ["TransactionService"] = new { Status = "Unknown", Url = _config["ServiceUrls:TransactionService"] },
            ["RiskService"] = new { Status = "Unknown", Url = _config["ServiceUrls:RiskService"] },
            ["PaymentService"] = new { Status = "Unknown", Url = _config["ServiceUrls:PaymentService"] },
            ["ComplianceService"] = new { Status = "Unknown", Url = _config["ServiceUrls:ComplianceService"] },
        };

        // Probe the PIN Encryption Service health endpoint to get its live status.
        // This makes a real HTTP call to the service rather than just showing "Unknown".
        var pinStatus = await ProbeServiceHealthAsync("PinEncryptionService", "/api/hsm/health");
        services["PinEncryptionService"] = new
        {
            Status = pinStatus,
            Url = _config["ServiceUrls:PinEncryptionService"]
        };

        // Ok() returns HTTP 200 with the anonymous object serialized as JSON.
        return Ok(new
        {
            Status = "Healthy",
            Timestamp = DateTime.UtcNow,
            Services = services
        });
    }

    // --------------------------------------------------------------------------
    // [HttpGet("status")] - Maps to GET /api/gateway/status
    // [Authorize] - Requires the request to include a valid JWT token.
    //   Without a valid token, ASP.NET returns 401 Unauthorized automatically.
    //   The token is validated using the parameters configured in Program.cs.
    // --------------------------------------------------------------------------
    [HttpGet("status")]
    [Authorize(Roles = "Admin,Auditor")]
    public IActionResult Status()
    {
        return Ok(new
        {
            // ActiveConnections is a property on ISseHub - the number of
            // currently connected SSE clients.
            ActiveSseConnections = _sseHub.ActiveConnections,
            // CurrentBackend is a property on AdaptiveEventBus that indicates
            // which event bus implementation is currently active (InMemory,
            // Redis, RabbitMQ, or Kafka). ToString() converts the enum value
            // to its string representation.
            EventBusBackend = _eventBus.CurrentBackend.ToString(),
            Timestamp = DateTime.UtcNow
        });
    }

    // Probes a downstream service's health endpoint. Returns "Healthy" if the
    // service responds with HTTP 200, "Unhealthy" if it fails, or "Unknown"
    // if the service URL is not configured.
    private async Task<string> ProbeServiceHealthAsync(string serviceName, string healthPath)
    {
        var url = _config[$"ServiceUrls:{serviceName}"];
        if (string.IsNullOrEmpty(url))
            return "Unknown";

        try
        {
            var client = _httpClientFactory.CreateClient();
            client.Timeout = TimeSpan.FromSeconds(2);
            var response = await client.GetAsync($"{url}{healthPath}");
            return response.IsSuccessStatusCode ? "Healthy" : "Unhealthy";
        }
        catch
        {
            return "Unhealthy";
        }
    }
}
